export const nickList = [
    "Nikita DM",
    "Vadim SH",
    "Artem K",
    "Marina F",
    "Alex D",
    "Kseniia O",
    "Victor S",
    "Dariia DB",
    "Yuliia Z",
    "Yuliia S",
    "Misha O",
    "Yurii V",
    "Anton U",
    "Nastya K",
    "Sergii Ch",
    "Alina O",
    "Varvara S",
    "Dmytro E",
    "Maks G",
    "Aleksei L",
    "Tanya D",
    "Nastya F",
    "Dima Z",
    "Inna D",
    "Ivan D",
    "Evheniia P",
    "Victoriia G",
    "Yehor B",
    "Karina B",
    "Yuliia V",
    "Dmytro N",
    "Nikita NV",
    "Svitlana KH",
    "Nick PR",
    "Sasha V",
    "Anna M",
    "Maks F",
    "Lesia K",
    "Victoriia E",
    "Andrii GL",
    "Ksenia D",
    "Anastasiia B",
    "Misha KR",
    "Aleksei N",
    "Yaroslav F",
    "Dasha V",
    "Alex M",
    "Tanya M",
    "Liza V",
    "Dasha F",
    "Artem KL",
    "Ilona B",
    "Kate N",
    "Juliia T",
    "Yana K",
    "Sasha K",
    "Yurii P",
    "Igor Y",
    "Bohdan SH",
    "Ivan KL"
]

export const emailList = [
    "domitrak.nikita@services.insidemaps.com",
    "shvets.vadym@services.insidemaps.com",
    "opryshko.kseniia@services.insidemaps.com",
    "dubrovskii.oleksii@services.insidemaps.com",
    "zots.yuliia@services.insidemaps.com",
    "kornienko.artem@services.insidemaps.com",
    "safronov.victor@services.insidemaps.com",
    "vitkovska.iryna@services.insidemaps.com",
    "volnianskii.yurii@services.insidemaps.com",
    "ushakov.anton@services.insidemaps.com",
    "kovalenko.anastasiia@services.insidemaps.com",
    "chaban.sergii@services.insidemaps.com",
    "ostashevska.alina@services.insidemaps.com",
    "safronova.varvara@services.insidemaps.com",
    "lozova.alina@services.insidemaps.com",
    "gladun.maksym@services.insidemaps.com",
    "fomenko.maryna@services.insidemaps.com",
    "lysenoi.oleksii@services.insidemaps.com",
    "derkach.tetiana@services.insidemaps.com",
    "kolishenko.nataliia@services.insidemaps.com",
    "firsiva.anastasiia@services.insidemaps.com",
    "zahrunnyi.dmytro@services.insidemaps.com",
    "demianenko.inna@services.insidemaps.com",
    "novikov.dmytro@services.insidemaps.com",
    "novytskyi.nikita@services.insidemaps.com",
    "khomenko.svitlana@services.insidemaps.com",
    "proskurnia.mykola@services.insidemaps.com",
    "varyvoda.oleksandr@services.insidemaps.com",
    "moskalenko.anna@services.insidemaps.com",
    "fedorov.maksym@services.insidemaps.com",
    "kokosha.olesia@services.insidemaps.com",
    "svystun.inna@services.insidemaps.com",
    "yevseyeva.viktoriia@services.insidemaps.com",
    "galas.andrii@services.insidemaps.com",
    "druz.ksennia@services.insidemaps.com",
    "fadieiev.yaroslav@services.insidemaps.com",
    "valytska.daria@services.insidemaps.com",
    "manziuk.olexii@services.insidemaps.com",
    "goretaia.lika@services.insidemaps.com",
    "mizina.tetiana@services.insidemaps.com",
    "vlasenko.elyzaveta@services.insidemaps.com",
    "fofanova.daryna@services.insidemaps.com",
    "klymok.artem@services.insidemaps.com",
    "belokon.ilona@services.insidemaps.com",
    "nesterenko.kateryna@services.insidemaps.com",
    "sevostianova.yuliia@services.insidemaps.com",
    "tarazevich.yuliia@services.insidemaps.com",
]

